export const terms = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sed massa in massa dignissim congue. Suspendisse potenti. Ut rutrum tortor eget facilisis fringilla. Nam pellentesque laoreet leo, ac posuere dui sagittis et. Sed sed vulputate est. Donec egestas, enim nec hendrerit gravida, tortor ante cursus magna, non feugiat nibh dolor nec justo. Sed lectus ex, convallis tristique bibendum eget, posuere quis enim. Donec quis tellus facilisis, ullamcorper eros quis, pellentesque turpis. Phasellus tincidunt massa in lectus dictum hendrerit. Curabitur nulla diam, congue non malesuada dignissim, consectetur ac ipsum. Nam in magna vitae diam lacinia dictum at eu nisi.

Nullam congue libero vitae efficitur tincidunt. Etiam ipsum metus, scelerisque ac tempor quis, pretium ut nibh. In sodales pellentesque elit, vitae tempor sem sollicitudin id. Maecenas pretium ac nunc sit amet accumsan. Curabitur nisl velit, rhoncus ut semper aliquam, auctor eget neque. Aenean in condimentum magna. Nullam vel mi lectus. Donec justo magna, ultricies rhoncus metus id, consectetur rutrum velit. Suspendisse potenti. Nulla quis felis auctor, lobortis tellus eu, auctor tortor. Suspendisse dictum, sapien non pellentesque rhoncus, purus ex porta nunc, eget tincidunt tortor lorem ac dui. Nullam vulputate eu mi nec finibus. Proin ac risus dictum elit ullamcorper cursus ac id lacus.

Donec tellus quam, facilisis eget ante vitae, blandit condimentum eros. Morbi sit amet dapibus libero. Quisque ultricies pretium finibus. Nullam vitae velit consectetur, sagittis magna et, rutrum augue. Fusce maximus eget mauris nec aliquet. Sed diam quam, fermentum sit amet lorem vel, dapibus molestie eros. Donec sit amet aliquet ligula. Morbi nulla neque, efficitur vitae commodo non, efficitur nec elit. Duis ipsum ante, euismod vel molestie nec, tempus at lectus. Nullam turpis sem, feugiat quis vehicula et, varius ut ante. Praesent rutrum tortor ut feugiat egestas.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sed massa in massa dignissim congue. Suspendisse potenti. Ut rutrum tortor eget facilisis fringilla. Nam pellentesque laoreet leo, ac posuere dui sagittis et. Sed sed vulputate est. Donec egestas, enim nec hendrerit gravida, tortor ante cursus magna, non feugiat nibh dolor nec justo. Sed lectus ex, convallis tristique bibendum eget, posuere quis enim. Donec quis tellus facilisis, ullamcorper eros quis, pellentesque turpis. Phasellus tincidunt massa in lectus dictum hendrerit. Curabitur nulla diam, congue non malesuada dignissim, consectetur ac ipsum. Nam in magna vitae diam lacinia dictum at eu nisi.

Nullam congue libero vitae efficitur tincidunt. Etiam ipsum metus, scelerisque ac tempor quis, pretium ut nibh. In sodales pellentesque elit, vitae tempor sem sollicitudin id. Maecenas pretium ac nunc sit amet accumsan. Curabitur nisl velit, rhoncus ut semper aliquam, auctor eget neque. Aenean in condimentum magna. Nullam vel mi lectus. Donec justo magna, ultricies rhoncus metus id, consectetur rutrum velit. Suspendisse potenti. Nulla quis felis auctor, lobortis tellus eu, auctor tortor. Suspendisse dictum, sapien non pellentesque rhoncus, purus ex porta nunc, eget tincidunt tortor lorem ac dui. Nullam vulputate eu mi nec finibus. Proin ac risus dictum elit ullamcorper cursus ac id lacus.

Donec tellus quam, facilisis eget ante vitae, blandit condimentum eros. Morbi sit amet dapibus libero. Quisque ultricies pretium finibus. Nullam vitae velit consectetur, sagittis magna et, rutrum augue. Fusce maximus eget mauris nec aliquet. Sed diam quam, fermentum sit amet lorem vel, dapibus molestie eros. Donec sit amet aliquet ligula. Morbi nulla neque, efficitur vitae commodo non, efficitur nec elit. Duis ipsum ante, euismod vel molestie nec, tempus at lectus. Nullam turpis sem, feugiat quis vehicula et, varius ut ante. Praesent rutrum tortor ut feugiat egestas.

`;
